---
title: "UK_life_expectancy"
author: "joedinoto"
date: "10/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warnings=FALSE, echo=FALSE, message=FALSE}
# libraries
library(tidyverse)
```


```{r warnings=FALSE, echo=FALSE, message=FALSE, cache=TRUE}
# obtain the data
url = "https://data.london.gov.uk/download/life-expectancy-birth-and-age-65-ward/38b6745f-168a-493d-9ff4-2b3ba63e86f2/life-expectancy-ward-at-Birth.csv"
UK_life_expentancy_original <- readr::read_csv(url)
```

```{r}
# Local authority, males, avg life expectancy, by year
UK_life_expentancy_small <- UK_life_expentancy_original %>%
  select(`Local Authority`,matches("(Male;Life)"), -matches("female")) 
```
```{r}
# rename column headers to only year
  names(UK_life_expentancy_small)[2:13] <- 1999:2010
unique(UK_life_expentancy_small$`Local Authority`) # number of unique Local Authorities
sum(is.na(UK_life_expentancy_small$`Local Authority`)) # count of NAs
```
```{r}
# boxplots for each of the 33 wards, average of lifespan by year
```


